version: 2.1
orbs:
  elixir: membraneframework/elixir@1

commands:
  save_deps_cache:
    steps:
      - save_cache:
          key: v1-mix-deps-cache-{{ checksum "mix.lock" }}
          paths: ["deps"]
  restore_deps_cache:
    steps:
      - restore_cache:
          keys:
            - v1-mix-deps-cache-{{ checksum "mix.lock" }}
            - v1-mix-deps-cache-
  workspace_init:
    steps:
      - checkout
      - restore_deps_cache
      - run: mix deps.clean --unused
      - run: mix deps.get
      - save_deps_cache
  save_build_cache:
    parameters:
      env:
        description: Mix environment
        type: string
        default: dev
    steps:
      - save_cache:
          key: v1-build-cache-{{ arch }}-<< parameters.env >>-{{ checksum "mix.lock" }}
          paths: ["_build/<< parameters.env >>"]
  restore_build_cache:
    parameters:
      env:
        description: Mix environment
        type: string
        default: dev
    steps:
      - restore_cache:
          keys:
            - v1-build-cache-{{ arch }}-<< parameters.env >>-{{ checksum "mix.lock" }}
            - v1-build-cache-{{ arch }}-<< parameters.env >>-
            - v1-build-cache-{{ arch }}-
            - v1-build-cache-
  gen_version_file:
    steps:
      - run: asdf current erlang > .runtime_version
      - run: asdf current elixir >> .runtime_version
  save_plt_cache:
    steps:
      - save_cache:
          key: v1-dialyzer-cache-{{ checksum ".runtime_version" }}-{{ checksum "mix.lock" }}
          paths: "priv/plts"
  restore_plt_cache:
    steps:
      - restore_cache:
          keys:
            - v1-dialyzer-cache-{{ checksum ".runtime_version" }}-{{ checksum "mix.lock" }}
            - v1-dialyzer-cache-{{ checksum ".runtime_version" }}-
            - v1-dialyzer-cache-

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test
      - elixir/test
      - elixir/lint
